CREATE DATABASE IF NOT EXISTS musika_db;
USE musika_db;
CREATE TABLE IF NOT EXISTS users (
    user_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    profile_vibe VARCHAR(50) DEFAULT 'Chill',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);